package com.mshernandez.vertconomy.wallet_interface.responses;

import com.google.gson.annotations.SerializedName;
import com.mshernandez.vertconomy.wallet_interface.WalletResponse;

public class ValidateAddressResponse extends WalletResponse<ValidateAddressResponse.Result>
{
    public class Result
    {
        /**
         * If the address is valid or not.
         * If not, all other properties are invalid.
         */
        @SerializedName("isvalid")
        public boolean isValid;

        /**
         * The address validated.
         */
        public String address;

        /**
         * The hex-encoded scriptPubKey generated by the address.
         */
        public String scriptPubKey;

        /**
         * If the key is a script.
         */
        @SerializedName("isscript")
        public boolean isScript;

        /**
         * If the address is a witness address.
         */
        @SerializedName("iswitness")
        public boolean isWitness;

        /**
         * The version number of the witness program.
         */
        @SerializedName("witness_version")
        public int witnessVersion;

        /**
         * The hex value of the witness program.
         */
        @SerializedName("witness_program")
        public String witnessProgram;
    }
}
