###################################
# Wallet API & Transactions
###################################

# RPC Wallet API Authentication, Please Change Defaults
user: vtcuser
pass: vtcpass
uri: http://127.0.0.1:5888

# Minimum Confirmations To Consider Deposits Valid
min-deposit-confirmations: 6

# Minimum Confirmations To Use Change Outputs
min-change-confirmations: 1

# Target Number Of Blocks To Confirm Withdrawals
target-block-time: 2

###################################
# Coin Information & Representation
###################################

# Coin Symbol
symbol: VTC
base-unit: sat

# Supported: base, micro, milli, full
scale: base

###################################
# General Plugin Behavior
###################################

# Experimental Vault Integration - Risk Of Lost Funds
vault-integration: false

# Automatically Configure Essentials Economy Commands If Found
configure-essentials: false

###################################
# Development Settings: CAREFUL
###################################

# SECURITY RISK: Enable H2 Web Console For DB Insight
enable-h2-console: false