main: com.mshernandez.vertconomy.App
name: Vertconomy
version: 0.0.1
api-version: 1.16
depend: [Vault]
loadbefore: [Essentials]

commands:
  balance:
    description: Allows a player to check their vertconomy balance.
    aliases: [bal]
    usage: /balance
    permission: vertconomy.balance
  deposit:
    description: Allows a player to deposit crypto into their vertconomy account.
    usage: /deposit
    permission: vertconomy.deposit
  