# Metadata
name: Vertconomy
version: 0.0.1
description: Vertcoin support for your server including in-game deposits, transfers, and withdrawals.
author: https://github.com/mshernandez5
website: https://github.com/mshernandez5/vertconomy

# Loading
main: com.mshernandez.vertconomy.App
api-version: 1.17
softdepend: [Vault]

# Commands
commands:
  balance:
    description: Check your vertconomy account balance.
    aliases: [bal]
    usage: /balance [player]
    permission: vertconomy.balance
  deposit:
    description: Deposit cryptocurrency into your vertconomy account.
    usage: /deposit
    permission: vertconomy.deposit
  pay:
    description: Send cryptocurrency to another player.
    usage: /pay [amount] [player]
    permission: vertconomy.pay
  withdraw:
    description: Withdraw cryptocurrency to your wallet.
    usage: /withdraw [amount | all] [address]
    permission: vertconomy.withdraw
  vertconomy:
    description: Show plugin information and wallet connection status.
    usage: /vertconomy
    permission: vertconomy.status

# Permissions
permissions:
  verconomy.balance:
    description: Allows players to use the /balance command.
    default: op
  vertconomy.balance.others:
    description: Allows players to see other player balances.
    default: op
    children:
      vertconomy.balance: true
  vertconomy.deposit:
    description: Allows players to use the /deposit command.
    default: op
  vertconomy.pay:
    description: Allows players to use the /pay command.
    default: op
  vertconomy.withdraw:
    description: Allows players to use the /withdraw command.
    default: op
  vertconomy.status:
    description: Allows players to use the /vertconomy command.
    default: op